from .sources import (
    OPENSKY_AUTH_URL,
    AIRCRAFT_IN_AREA_SOURCE_URL,
    ROUTE_DETAILS_HX_SOURCE_URL,
    ROUTE_DETAILS_SB_SOURCE_URL,
    AIRCRAFT_PHOTO_AD_SOURCE_URL,
    AIRCRAFT_PHOTO_AD_STATIC_URL,
    AIRCRAFT_PHOTO_HX_SOURCE_URL,
    AIRCRAFT_PHOTO_PS_SOURCE_URL,
    AIRPORT_DETAILS_AD_SOURCE_URL,
    AIRPORT_DETAILS_HX_SOURCE_URL,
    AIRCRAFT_DETAILS_FD_SOURCE_URL,
    AIRCRAFT_DETAILS_HX_SOURCE_URL,
    AIRCRAFT_DETAILS_SB_SOURCE_URL,
)
from .constants import EARTH_RADIUS, DEFAULT_DISTANCE_FROM_POINT

__all__ = [
    "AIRCRAFT_DETAILS_FD_SOURCE_URL",
    "AIRCRAFT_DETAILS_HX_SOURCE_URL",
    "AIRCRAFT_DETAILS_SB_SOURCE_URL",
    "AIRCRAFT_IN_AREA_SOURCE_URL",
    "AIRCRAFT_PHOTO_AD_SOURCE_URL",
    "AIRCRAFT_PHOTO_AD_STATIC_URL",
    "AIRCRAFT_PHOTO_HX_SOURCE_URL",
    "AIRCRAFT_PHOTO_PS_SOURCE_URL",
    "AIRPORT_DETAILS_AD_SOURCE_URL",
    "AIRPORT_DETAILS_HX_SOURCE_URL",
    "DEFAULT_DISTANCE_FROM_POINT",
    "EARTH_RADIUS",
    "OPENSKY_AUTH_URL",
    "ROUTE_DETAILS_HX_SOURCE_URL",
    "ROUTE_DETAILS_SB_SOURCE_URL",
]
